documentation:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**']

skills:
  - changed-files:
    - any-glob-to-any-file: ['**/skills/**', '**/SKILL.md']

plugin:
  - changed-files:
    - any-glob-to-any-file: ['plugins/**']

configuration:
  - changed-files:
    - any-glob-to-any-file: ['**/*.json', '.claude-plugin/**']

ci/cd:
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**', '.github/**']

dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package*.json', 'yarn.lock', 'pnpm-lock.yaml']
