#!/usr/bin/env node
'use strict';
/**
 * Automated daily site-review health check for InvestSkill.
 *
 * Runs the repo's automatable review checks (build, internal links, test
 * suite, prompt validation, version parity, count consistency) and writes a
 * dated markdown report to  qa/site_review_YYYYMMDD.md.
 *
 * Usage:  node scripts/site-review.js        (npm run review)
 * CI:     .github/workflows/site-review.yml  (daily cron)
 *
 * Exit code: 0 if every check passed, 1 otherwise (the report is still
 * written either way, so CI can commit it with `if: always()`).
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const QA_DIR = path.join(ROOT, 'qa');

// ── Date stamp (UTC, so cron runs are deterministic) ─────────────────────────
const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const stamp = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(now.getUTCDate())}`;
const isoDate = now.toISOString().slice(0, 10);

// ── Helpers ──────────────────────────────────────────────────────────────────
function run(cmd) {
  try {
    const out = execSync(cmd, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
    return { ok: true, out };
  } catch (e) {
    return { ok: false, out: `${e.stdout || ''}${e.stderr || ''}` };
  }
}
const readJSON = (p) => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));
const firstMatch = (s, re) => { const m = s.match(re); return m ? m[0].trim() : ''; };

// ── Repo snapshot ─────────────────────────────────────────────────────────────
const skillsDir = path.join(ROOT, 'plugins/us-stock-analysis/skills');
const skillCount = fs.readdirSync(skillsDir).filter(d => fs.statSync(path.join(skillsDir, d)).isDirectory()).length;
const promptCount = fs.readdirSync(path.join(ROOT, 'prompts')).filter(f => f.endsWith('.md')).length;
const OUTPUT_TOOLS = ['report-generator'];
const advertised = skillCount - OUTPUT_TOOLS.length;

const pkg = readJSON('package.json');
const plugin = readJSON('plugins/us-stock-analysis/.claude-plugin/plugin.json');
const marketplace = readJSON('.claude-plugin/marketplace.json');
const versions = [pkg.version, plugin.version, marketplace.metadata && marketplace.metadata.version];
const versionOk = new Set(versions.filter(Boolean)).size === 1;

// ── Checks ────────────────────────────────────────────────────────────────────
const checks = [];

const build = run('node docs/build-site.js');
checks.push({ name: 'Site build', ok: build.ok, detail: build.ok ? 'built _site/' : 'build FAILED' });

const links = run('node scripts/check-links.js');
checks.push({
  name: 'Internal links',
  ok: links.ok,
  detail: firstMatch(links.out, /(Link check passed[^\n]*|\d+ broken internal link[^\n]*)/i) || (links.ok ? 'ok' : 'broken links'),
});

const tests = run('node scripts/test-skills.js');
const passed = (tests.out.match(/Passed:\s*(\d+)/) || [])[1] || '?';
const failed = (tests.out.match(/Failed:\s*(\d+)/) || [])[1] || '?';
checks.push({ name: 'Test suite', ok: tests.ok, detail: `${passed} passed, ${failed} failed` });

const validate = run('node scripts/validate-prompts.js');
checks.push({ name: 'Prompt validation', ok: validate.ok, detail: validate.ok ? 'valid' : 'issues found' });

checks.push({ name: 'Version parity', ok: versionOk, detail: [...new Set(versions.filter(Boolean))].join(' / ') });
checks.push({ name: 'Skills ↔ prompts parity', ok: skillCount === promptCount, detail: `${skillCount} skills / ${promptCount} prompts` });

let pageCount = 0;
try { pageCount = fs.readdirSync(path.join(ROOT, '_site')).filter(f => f.endsWith('.html')).length; } catch { /* not built */ }

const allOk = checks.every(c => c.ok);

// ── Report ──────────────────────────────────────────────────────────────────
let md = `# Site Review — ${isoDate}\n\n`;
md += `*Automated daily health check for InvestSkill. Generated by \`scripts/site-review.js\`. `;
md += `For the full qualitative review and roadmap, see [PROJECT-REVIEW.md](PROJECT-REVIEW.md).*\n\n`;
md += `**Overall: ${allOk ? '✅ PASS' : '❌ ATTENTION NEEDED'}**\n\n`;

md += `## Checks\n\n| Check | Status | Detail |\n|---|:--:|---|\n`;
checks.forEach(c => { md += `| ${c.name} | ${c.ok ? '✅' : '❌'} | ${c.detail || ''} |\n`; });

md += `\n## Snapshot\n\n| Metric | Value |\n|---|---|\n`;
md += `| Version | ${plugin.version} |\n`;
md += `| Skill directories | ${skillCount} |\n`;
md += `| Universal prompts | ${promptCount} |\n`;
md += `| Advertised frameworks | ${advertised} (${skillCount} − ${OUTPUT_TOOLS.length} output tool) |\n`;
md += `| Built HTML pages | ${pageCount} |\n`;

if (!allOk) {
  md += `\n## ⚠️ Failing check output\n\n`;
  checks.filter(c => !c.ok).forEach(c => {
    const src = c.name === 'Test suite' ? tests.out : c.name === 'Internal links' ? links.out : c.name === 'Site build' ? build.out : validate.out;
    md += `### ${c.name}\n\n\`\`\`\n${(src || '').trim().slice(-1200)}\n\`\`\`\n\n`;
  });
}

md += `\n---\n*Report ${stamp} · generated ${now.toISOString()}*\n`;

fs.mkdirSync(QA_DIR, { recursive: true });
const outFile = path.join(QA_DIR, `site_review_${stamp}.md`);
fs.writeFileSync(outFile, md);

console.log(`✓ wrote qa/site_review_${stamp}.md — overall ${allOk ? 'PASS' : 'FAIL'}`);
checks.forEach(c => console.log(`  ${c.ok ? '✅' : '❌'} ${c.name}: ${c.detail}`));
process.exit(allOk ? 0 : 1);
